apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-config
  namespace: aula-k8s
data:
  config.yaml: |
    rules:
    # Métrica baseada em requisições HTTP
    - seriesQuery: 'http_requests_total{namespace="aula-k8s"}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "http_requests_total"
        as: "requests_per_second"
      metricsQuery: 'sum(rate(<<.Series>>[5m])) by (<<.GroupBy>>)'
    
    # Métrica baseada em tempo de resposta
    - seriesQuery: 'http_request_duration_seconds{namespace="aula-k8s"}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "http_request_duration_seconds"
        as: "response_time_seconds"
      metricsQuery: 'histogram_quantile(0.95, sum(rate(<<.Series>>_bucket[5m])) by (<<.GroupBy>>)'
    
    # Métrica baseada em erros HTTP
    - seriesQuery: 'http_requests_total{namespace="aula-k8s", status=~"4..|5.."}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "http_requests_total"
        as: "error_rate"
      metricsQuery: 'sum(rate(<<.Series>>[5m])) by (<<.GroupBy>>)'
---
# HPA usando métricas customizadas
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-custom-metrics
  namespace: aula-k8s
  annotations:
    description: "HPA usando métricas customizadas além de CPU/memória"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 20
  metrics:
  # Métrica baseada em CPU (padrão)
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # Métrica baseada em requisições por segundo
  - type: Object
    object:
      metric:
        name: requests_per_second
      describedObject:
        apiVersion: v1
        kind: Service
        name: php-apache
      target:
        type: AverageValue
        averageValue: 100
  # Métrica baseada em tempo de resposta
  - type: Object
    object:
      metric:
        name: response_time_seconds
      describedObject:
        apiVersion: v1
        kind: Service
        name: php-apache
      target:
        type: AverageValue
        averageValue: 0.5
