apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-advanced
  namespace: aula-k8s
  annotations:
    description: "HPA avançado com múltiplas métricas e comportamentos personalizados"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 15
  # Comportamento de escalabilidade
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
  # Múltiplas métricas
  metrics:
  # Métrica baseada em CPU
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # Métrica baseada em memória
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Métrica baseada em requisições HTTP (se disponível)
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: v1
        kind: Service
        name: php-apache
      target:
        type: AverageValue
        averageValue: 100
---
# Configuração de métricas customizadas
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-config
  namespace: aula-k8s
data:
  config.yaml: |
    rules:
    - seriesQuery: 'http_requests_total{namespace="aula-k8s"}'
      resources:
        overrides:
          namespace:
            resource: namespace
      name:
        matches: "http_requests_total"
        as: "requests_per_second"
      metricsQuery: 'sum(rate(<<.Series>>[5m])) by (<<.GroupBy>>)'
