apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: php-apache-vpa
  namespace: aula-k8s
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: php-apache
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      minAllowed:
        cpu: 100m
        memory: 50Mi
      maxAllowed:
        cpu: 1
        memory: 500Mi
      controlledValues: RequestsAndLimits
---
# Configuração de métricas customizadas para VPA
apiVersion: v1
kind: ConfigMap
metadata:
  name: vpa-metrics-config
  namespace: aula-k8s
data:
  config.yaml: |
    apiVersion: vpa.autoscaling.k8s.io/v1
    kind: VPAConfig
    spec:
      recommendationOnly: false
      containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 1
          memory: 500Mi
        controlledValues: RequestsAndLimits
