apiVersion: v1
kind: Namespace
metadata:
  name: aula-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: aula-k8s
  labels:
    app: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
        - name: php-apache
          image: registry.k8s.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: aula-k8s
spec:
  type: ClusterIP
  selector:
    app: php-apache
  ports:
    - name: http
      port: 80
      targetPort: 80
